# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/fanxu/Documents/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Users/fanxu/Documents/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fanxu/www/go/src/github.com/Qitmeer/x17r

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fanxu/www/go/src/github.com/Qitmeer/x17r

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/fanxu/Documents/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/fanxu/Documents/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fanxu/www/go/src/github.com/Qitmeer/x17r/CMakeFiles /Users/fanxu/www/go/src/github.com/Qitmeer/x17r/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fanxu/www/go/src/github.com/Qitmeer/x17r/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named x16r_hash

# Build rule for target.
x16r_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x16r_hash
.PHONY : x16r_hash

# fast build rule for target.
x16r_hash/fast:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/build
.PHONY : x16r_hash/fast

aes/aes.o: aes/aes.c.o

.PHONY : aes/aes.o

# target to build an object file
aes/aes.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/aes/aes.c.o
.PHONY : aes/aes.c.o

aes/aes.i: aes/aes.c.i

.PHONY : aes/aes.i

# target to preprocess a source file
aes/aes.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/aes/aes.c.i
.PHONY : aes/aes.c.i

aes/aes.s: aes/aes.c.s

.PHONY : aes/aes.s

# target to generate assembly for a file
aes/aes.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/aes/aes.c.s
.PHONY : aes/aes.c.s

algo/blake.o: algo/blake.c.o

.PHONY : algo/blake.o

# target to build an object file
algo/blake.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/blake.c.o
.PHONY : algo/blake.c.o

algo/blake.i: algo/blake.c.i

.PHONY : algo/blake.i

# target to preprocess a source file
algo/blake.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/blake.c.i
.PHONY : algo/blake.c.i

algo/blake.s: algo/blake.c.s

.PHONY : algo/blake.s

# target to generate assembly for a file
algo/blake.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/blake.c.s
.PHONY : algo/blake.c.s

algo/bmw.o: algo/bmw.c.o

.PHONY : algo/bmw.o

# target to build an object file
algo/bmw.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/bmw.c.o
.PHONY : algo/bmw.c.o

algo/bmw.i: algo/bmw.c.i

.PHONY : algo/bmw.i

# target to preprocess a source file
algo/bmw.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/bmw.c.i
.PHONY : algo/bmw.c.i

algo/bmw.s: algo/bmw.c.s

.PHONY : algo/bmw.s

# target to generate assembly for a file
algo/bmw.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/bmw.c.s
.PHONY : algo/bmw.c.s

algo/cubehash.o: algo/cubehash.c.o

.PHONY : algo/cubehash.o

# target to build an object file
algo/cubehash.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/cubehash.c.o
.PHONY : algo/cubehash.c.o

algo/cubehash.i: algo/cubehash.c.i

.PHONY : algo/cubehash.i

# target to preprocess a source file
algo/cubehash.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/cubehash.c.i
.PHONY : algo/cubehash.c.i

algo/cubehash.s: algo/cubehash.c.s

.PHONY : algo/cubehash.s

# target to generate assembly for a file
algo/cubehash.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/cubehash.c.s
.PHONY : algo/cubehash.c.s

algo/echo.o: algo/echo.c.o

.PHONY : algo/echo.o

# target to build an object file
algo/echo.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/echo.c.o
.PHONY : algo/echo.c.o

algo/echo.i: algo/echo.c.i

.PHONY : algo/echo.i

# target to preprocess a source file
algo/echo.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/echo.c.i
.PHONY : algo/echo.c.i

algo/echo.s: algo/echo.c.s

.PHONY : algo/echo.s

# target to generate assembly for a file
algo/echo.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/echo.c.s
.PHONY : algo/echo.c.s

algo/fugue.o: algo/fugue.c.o

.PHONY : algo/fugue.o

# target to build an object file
algo/fugue.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/fugue.c.o
.PHONY : algo/fugue.c.o

algo/fugue.i: algo/fugue.c.i

.PHONY : algo/fugue.i

# target to preprocess a source file
algo/fugue.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/fugue.c.i
.PHONY : algo/fugue.c.i

algo/fugue.s: algo/fugue.c.s

.PHONY : algo/fugue.s

# target to generate assembly for a file
algo/fugue.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/fugue.c.s
.PHONY : algo/fugue.c.s

algo/groestl.o: algo/groestl.c.o

.PHONY : algo/groestl.o

# target to build an object file
algo/groestl.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/groestl.c.o
.PHONY : algo/groestl.c.o

algo/groestl.i: algo/groestl.c.i

.PHONY : algo/groestl.i

# target to preprocess a source file
algo/groestl.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/groestl.c.i
.PHONY : algo/groestl.c.i

algo/groestl.s: algo/groestl.c.s

.PHONY : algo/groestl.s

# target to generate assembly for a file
algo/groestl.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/groestl.c.s
.PHONY : algo/groestl.c.s

algo/hamsi.o: algo/hamsi.c.o

.PHONY : algo/hamsi.o

# target to build an object file
algo/hamsi.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi.c.o
.PHONY : algo/hamsi.c.o

algo/hamsi.i: algo/hamsi.c.i

.PHONY : algo/hamsi.i

# target to preprocess a source file
algo/hamsi.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi.c.i
.PHONY : algo/hamsi.c.i

algo/hamsi.s: algo/hamsi.c.s

.PHONY : algo/hamsi.s

# target to generate assembly for a file
algo/hamsi.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi.c.s
.PHONY : algo/hamsi.c.s

algo/hamsi_helper.o: algo/hamsi_helper.c.o

.PHONY : algo/hamsi_helper.o

# target to build an object file
algo/hamsi_helper.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi_helper.c.o
.PHONY : algo/hamsi_helper.c.o

algo/hamsi_helper.i: algo/hamsi_helper.c.i

.PHONY : algo/hamsi_helper.i

# target to preprocess a source file
algo/hamsi_helper.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi_helper.c.i
.PHONY : algo/hamsi_helper.c.i

algo/hamsi_helper.s: algo/hamsi_helper.c.s

.PHONY : algo/hamsi_helper.s

# target to generate assembly for a file
algo/hamsi_helper.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/hamsi_helper.c.s
.PHONY : algo/hamsi_helper.c.s

algo/jh.o: algo/jh.c.o

.PHONY : algo/jh.o

# target to build an object file
algo/jh.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/jh.c.o
.PHONY : algo/jh.c.o

algo/jh.i: algo/jh.c.i

.PHONY : algo/jh.i

# target to preprocess a source file
algo/jh.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/jh.c.i
.PHONY : algo/jh.c.i

algo/jh.s: algo/jh.c.s

.PHONY : algo/jh.s

# target to generate assembly for a file
algo/jh.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/jh.c.s
.PHONY : algo/jh.c.s

algo/keccak.o: algo/keccak.c.o

.PHONY : algo/keccak.o

# target to build an object file
algo/keccak.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/keccak.c.o
.PHONY : algo/keccak.c.o

algo/keccak.i: algo/keccak.c.i

.PHONY : algo/keccak.i

# target to preprocess a source file
algo/keccak.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/keccak.c.i
.PHONY : algo/keccak.c.i

algo/keccak.s: algo/keccak.c.s

.PHONY : algo/keccak.s

# target to generate assembly for a file
algo/keccak.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/keccak.c.s
.PHONY : algo/keccak.c.s

algo/luffa.o: algo/luffa.c.o

.PHONY : algo/luffa.o

# target to build an object file
algo/luffa.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/luffa.c.o
.PHONY : algo/luffa.c.o

algo/luffa.i: algo/luffa.c.i

.PHONY : algo/luffa.i

# target to preprocess a source file
algo/luffa.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/luffa.c.i
.PHONY : algo/luffa.c.i

algo/luffa.s: algo/luffa.c.s

.PHONY : algo/luffa.s

# target to generate assembly for a file
algo/luffa.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/luffa.c.s
.PHONY : algo/luffa.c.s

algo/sha2big.o: algo/sha2big.c.o

.PHONY : algo/sha2big.o

# target to build an object file
algo/sha2big.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/sha2big.c.o
.PHONY : algo/sha2big.c.o

algo/sha2big.i: algo/sha2big.c.i

.PHONY : algo/sha2big.i

# target to preprocess a source file
algo/sha2big.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/sha2big.c.i
.PHONY : algo/sha2big.c.i

algo/sha2big.s: algo/sha2big.c.s

.PHONY : algo/sha2big.s

# target to generate assembly for a file
algo/sha2big.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/sha2big.c.s
.PHONY : algo/sha2big.c.s

algo/shabal.o: algo/shabal.c.o

.PHONY : algo/shabal.o

# target to build an object file
algo/shabal.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shabal.c.o
.PHONY : algo/shabal.c.o

algo/shabal.i: algo/shabal.c.i

.PHONY : algo/shabal.i

# target to preprocess a source file
algo/shabal.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shabal.c.i
.PHONY : algo/shabal.c.i

algo/shabal.s: algo/shabal.c.s

.PHONY : algo/shabal.s

# target to generate assembly for a file
algo/shabal.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shabal.c.s
.PHONY : algo/shabal.c.s

algo/shavite.o: algo/shavite.c.o

.PHONY : algo/shavite.o

# target to build an object file
algo/shavite.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shavite.c.o
.PHONY : algo/shavite.c.o

algo/shavite.i: algo/shavite.c.i

.PHONY : algo/shavite.i

# target to preprocess a source file
algo/shavite.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shavite.c.i
.PHONY : algo/shavite.c.i

algo/shavite.s: algo/shavite.c.s

.PHONY : algo/shavite.s

# target to generate assembly for a file
algo/shavite.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/shavite.c.s
.PHONY : algo/shavite.c.s

algo/simd.o: algo/simd.c.o

.PHONY : algo/simd.o

# target to build an object file
algo/simd.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/simd.c.o
.PHONY : algo/simd.c.o

algo/simd.i: algo/simd.c.i

.PHONY : algo/simd.i

# target to preprocess a source file
algo/simd.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/simd.c.i
.PHONY : algo/simd.c.i

algo/simd.s: algo/simd.c.s

.PHONY : algo/simd.s

# target to generate assembly for a file
algo/simd.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/simd.c.s
.PHONY : algo/simd.c.s

algo/skein.o: algo/skein.c.o

.PHONY : algo/skein.o

# target to build an object file
algo/skein.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/skein.c.o
.PHONY : algo/skein.c.o

algo/skein.i: algo/skein.c.i

.PHONY : algo/skein.i

# target to preprocess a source file
algo/skein.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/skein.c.i
.PHONY : algo/skein.c.i

algo/skein.s: algo/skein.c.s

.PHONY : algo/skein.s

# target to generate assembly for a file
algo/skein.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/skein.c.s
.PHONY : algo/skein.c.s

algo/whirlpool.o: algo/whirlpool.c.o

.PHONY : algo/whirlpool.o

# target to build an object file
algo/whirlpool.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/whirlpool.c.o
.PHONY : algo/whirlpool.c.o

algo/whirlpool.i: algo/whirlpool.c.i

.PHONY : algo/whirlpool.i

# target to preprocess a source file
algo/whirlpool.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/whirlpool.c.i
.PHONY : algo/whirlpool.c.i

algo/whirlpool.s: algo/whirlpool.c.s

.PHONY : algo/whirlpool.s

# target to generate assembly for a file
algo/whirlpool.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/algo/whirlpool.c.s
.PHONY : algo/whirlpool.c.s

x16r.o: x16r.c.o

.PHONY : x16r.o

# target to build an object file
x16r.c.o:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/x16r.c.o
.PHONY : x16r.c.o

x16r.i: x16r.c.i

.PHONY : x16r.i

# target to preprocess a source file
x16r.c.i:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/x16r.c.i
.PHONY : x16r.c.i

x16r.s: x16r.c.s

.PHONY : x16r.s

# target to generate assembly for a file
x16r.c.s:
	$(MAKE) -f CMakeFiles/x16r_hash.dir/build.make CMakeFiles/x16r_hash.dir/x16r.c.s
.PHONY : x16r.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... x16r_hash"
	@echo "... aes/aes.o"
	@echo "... aes/aes.i"
	@echo "... aes/aes.s"
	@echo "... algo/blake.o"
	@echo "... algo/blake.i"
	@echo "... algo/blake.s"
	@echo "... algo/bmw.o"
	@echo "... algo/bmw.i"
	@echo "... algo/bmw.s"
	@echo "... algo/cubehash.o"
	@echo "... algo/cubehash.i"
	@echo "... algo/cubehash.s"
	@echo "... algo/echo.o"
	@echo "... algo/echo.i"
	@echo "... algo/echo.s"
	@echo "... algo/fugue.o"
	@echo "... algo/fugue.i"
	@echo "... algo/fugue.s"
	@echo "... algo/groestl.o"
	@echo "... algo/groestl.i"
	@echo "... algo/groestl.s"
	@echo "... algo/hamsi.o"
	@echo "... algo/hamsi.i"
	@echo "... algo/hamsi.s"
	@echo "... algo/hamsi_helper.o"
	@echo "... algo/hamsi_helper.i"
	@echo "... algo/hamsi_helper.s"
	@echo "... algo/jh.o"
	@echo "... algo/jh.i"
	@echo "... algo/jh.s"
	@echo "... algo/keccak.o"
	@echo "... algo/keccak.i"
	@echo "... algo/keccak.s"
	@echo "... algo/luffa.o"
	@echo "... algo/luffa.i"
	@echo "... algo/luffa.s"
	@echo "... algo/sha2big.o"
	@echo "... algo/sha2big.i"
	@echo "... algo/sha2big.s"
	@echo "... algo/shabal.o"
	@echo "... algo/shabal.i"
	@echo "... algo/shabal.s"
	@echo "... algo/shavite.o"
	@echo "... algo/shavite.i"
	@echo "... algo/shavite.s"
	@echo "... algo/simd.o"
	@echo "... algo/simd.i"
	@echo "... algo/simd.s"
	@echo "... algo/skein.o"
	@echo "... algo/skein.i"
	@echo "... algo/skein.s"
	@echo "... algo/whirlpool.o"
	@echo "... algo/whirlpool.i"
	@echo "... algo/whirlpool.s"
	@echo "... x16r.o"
	@echo "... x16r.i"
	@echo "... x16r.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

